#!/bin/bash
# source the function lib
. /etc/init.d/functions

exec="/usr/bin/crow"
prog="crow"

lockdir=/var/lock/subsys

LOG_history=/var/log/crow-history.log
LOG_queue=/var/log/crow-queue.log
BRAND=generic

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

start () {
	[ -x $exec ] || exit 5
	[ -f $config ] || exit 6 

	for mode in history queue; do
		what="$prog $mode"
		lockfile=$lockdir/$(echo "$what" | tr ' ' _)
		if [ -f $lockfile ]; then
			echo >&2 "lockfile exists: $lockfile"
		else
			log=$(eval echo '$LOG_'$mode)
			cmd="$exec -b $BRAND $mode"
			echo -n $"Starting $what: "
			$cmd > $log &
			pid=$!
			retval=$?
			echo
			[ $retval -eq 0 ] && echo $pid > $lockfile
		fi
	done
}

stop () {
	for mode in history queue; do
		what="$prog $mode"
		lockfile=$lockdir/$(echo "$what" | tr ' ' _)
		if [ -f $lockfile ]; then
			echo -n $"Stopping $what: "
			kill $(cat $lockfile) && echo ok && rm -f $lockfile
		else
			echo >&2 "lockfile does not exist: $lockfile"
		fi
	done
}

restart () {
	stop
	start
}

rh_status () {
	status $prog
}

rh_status_q () {
	rh_status >/dev/null 2>&1
}


case "$1" in
	start)
		#rh_status_q && exit 0
		$1
		;;
	stop)
		#rh_status_q || exit 0
		$1
		;;
	restart)
		$1
		;;
	status)
		rh_status
		;;
	*)
		echo $"Usage: $0 {start|stop|status|restart}"
		exit 2
esac
exit $? 
