#!/bin/bash -x
# source the function lib
. /etc/init.d/functions

exec="/usr/bin/crow"
prog="crow"

lockfile=/var/lock/subsys/$prog

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

start() {
  [ -x $exec ] || exit 5
  [ -f $config ] || exit 6 
  echo -n $"Starting $prog: "
  retval=$?
  echo
  [ $reval -eq 0 ] && touch $lockfile
  return $retval
}

stop() {
  echo -n $"Stopping $prog: "
  retval=$?
  echo
  [ $retval -eq 0 ] && rm -f $lockfile
  return $retval
}

restart() {
  stop
  start
}

rh_status() {
  status $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
  start)
    rh_status_q && exit 0
    $1
    ;;
  stop)
    rh_status_q || exit 0
    $1
    ;;
  restart)
    $1
    ;;
  status)
    rh_status
    ;;
  *)
    echo $"Usage: $0 {start|stop|status|restart}"
    exit 2
esac
exit $? 
