#!/bin/bash
#
# chkconfig: 2345 90 60
#

# source the function lib
. /etc/init.d/functions

exec="/usr/bin/crow"
prog="crow"
lockdir=/var/lock/subsys

BRAND=generic

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

pidfile="/var/run/crow-${BRAND}-master.pid"

start () {
	[ -x $exec ] || exit 5
	[ -f $config ] || exit 6 
	[ -e $pidfile ] && { echo >&2 "pidfile $pidfile exists - not starting; exit 7; }

	daemon $prog -b ${BRAND}
}

stop () {
	if [ -e $pidfile ]; then
		echo -n $"Stopping $prog: "
		kill -INT $(cat $pidfile) && echo ok
	else
		echo >&2 "lockfile does not exist: $lockfile"
	fi
}

restart () {
	stop
	start
}

rh_status () {
	status $prog
}

rh_status_q () {
	rh_status >/dev/null 2>&1
}


case "$1" in
	start)
		#rh_status_q && exit 0
		$1
		;;
	stop)
		#rh_status_q || exit 0
		$1
		;;
	restart)
		$1
		;;
	status)
		rh_status
		;;
	*)
		echo $"Usage: $0 {start|stop|status|restart}"
		exit 2
esac
exit $? 
